name = "warpifydomainworker"
main = "src/app.ts"
compatibility_date = "2025-01-01"

browser = { binding = "BROWSER" }

compatibility_flags = [ "nodejs_compat" ]

[vars]
CF_API_TOKEN = "D_QHjtKtrXz_W0vvr7wTJkcTnA-vZFhbS5P6cNYT"
JWT_SECRET = "secret"
SMARTLEAD_API_BASE = "https://server.smartlead.ai/api/v1"

[[kv_namespaces]]
binding = "KV"
id = "9310dfa0d0984a70a9ec8e9075d89279"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "warpify"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
